version: '3'
services:
  redis:
    image: redis
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis.acl:/etc/redis/redis.acl
    ports:
      - "6379:6379"